site_name: Kubernetes FAQ
site_url: https://koletyst.github.io/kubernetes-faq
site_author: koletyst
site_description: Learn Kubernetes, flashcards, CKA, CKAD, interview questions.

repo_url: https://github.com/koletyst/kubernetes-faq/
repo_name: kubernetes-faq

theme:
  favicon: favicon.png
  icon:
    logo: material/kubernetes
  custom_dir: overrides
  features:
    - header.autohide
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/koletyst
      name: koletyst on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/koletyst
      name: koletyst on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/koletyst
      name: koletyst on LinkedIn

copyright: "&copy; 2020-2023 @koletyst"
