site_name: kubernetes-faq
site_url: https://katademy.github.io/kubernetes-faq
site_author: Icelyn Jennings
site_description: Learn Kubernetes

repo_url: https://github.com/katademy/kubernetes-faq/
repo_name: kubernetes-faq

theme:
  name: material
