site_name: kubernetes-faq
site_url: https://katademy.github.io/kubernetes-faq
site_author: Icelyn Jennings
site_description: Learn Kubernetes

repo_url: https://github.com/katademy/kubernetes-faq/
repo_name: kubernetes-faq

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode